---
# This is A sample Docker Compose that can be used to build the RF Controller Web Stack, it relies on the docker image being built first

services:
  socket-rf-transmitter:
    container_name: smart-rf-transmitter
    build:
      context: ./src
    # image: rf_transmitter:v1
    stdin_open: true
    tty: true
    environment:
      - TZ=Europe/London
      - TSMT_PIN_NUMBER= 11
#    devices:
#      - "/dev/gpiomem:/dev/gpiomem"
    ports:
      - 60000:60000
    privileged: true
    restart: unless-stopped
