[project]
name = "smart-rf-plug-transmitter"
version = "0.1.0"
description = "A Python project for transmitting signals to smart RF plugs using TCP or MQTT"
readme = "README.md"
license = { file = "../LICENSE" }
requires-python = ">=3.14"
dependencies = [
    "rpi.gpio>=0.7.1; sys_platform == 'linux'",
    "paho-mqtt>=2.1.0",

]
